# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  request_changes_workflow: false
  high_level_summary: false
  poem: false
  review_status: false
  review_details: false
  auto_review:
    enabled: false
    drafts: false
chat:
  auto_reply: false
issue_enrichment:
  auto_enrich:
    enabled: false
