# This populates the csrc/gemm/instantiations directory, and is run by setup.py.
# To control which kernels are actually compiled at build time, edit compiled_kernels.cfg.
import itertools
import os
from pathlib import Path

from pearl_gemm_build_utils.kernel_configs import (
    MatmulKernelConfig,
    NoisingAKernelConfig,
    NoisingBKernelConfig,
)

filename_type_to_cutlass_type = {
    "fp16": "cutlass::half_t",
    "int32": "int",
    "int": "int",
    "bf16": "cutlass::bfloat16_t",
}


def noisy_gemm_prelude() -> str:
    prelude = """#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_gemm_host.h"

    /* Autogenerated -- see generate_instantiations.py
    * run_pearl_gemm_<ElementOut, R, bM, bN, kStages, cM, cN, SkipReduction, SkipDenoising, EnableDebug>(PearlAPIParams& params, cudaStream_t stream);
    */

    """
    return prelude


def noising_A_prelude() -> str:
    prelude = """#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_noisingA_host.h"

    /* Autogenerated -- see generate_instantiations.py
    * run_pearl_noising_A_<ElementDenoise_AxEBL, R, bM_noising_A, bK_noising_A, kStages>(PearlAPIParams& params, cudaStream_t stream);
    */

    """
    return prelude


def noising_B_prelude() -> str:
    prelude = """#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_noisingB_host.h"

    /* Autogenerated -- see generate_instantiations.py
    * run_pearl_noising_B_<ElementDenoise_EARxBpEB, R, bN_noising_B, bK_noising_B, kStages>(PearlAPIParams& params, cudaStream_t stream);
    */

    """
    return prelude


def to_str(b: bool):
    return str(b).lower()


def gemm_decl(
    config: MatmulKernelConfig,
    out_type: str,
    SkipReduction: bool,
    SkipDenoising: bool,
    EnableDebug: bool,
) -> str:
    out_type = filename_type_to_cutlass_type[out_type]
    condition = "#if "
    if SkipReduction:
        condition += "!defined(DISABLE_SKIP_REDUCTION) && "
    if SkipDenoising:
        condition += "!defined(DISABLE_SKIP_DENOISING) && "
    if EnableDebug:
        condition += "!defined(DISABLE_DEBUG_MODE) && "
    condition = condition[:-4]
    decl = ""
    if condition:
        decl = condition + "\n"
    decl += f"\ttemplate void run_pearl_gemm_<{out_type}, {config.R}, {config.tile_size_m}, {config.tile_size_n}, {config.tile_size_k}, {config.pipeline_stages}, {config.cM}, {config.cN}, {to_str(SkipReduction)}, {to_str(SkipDenoising)}, {to_str(EnableDebug)}>(PearlAPIParams&, cudaStream_t);\n"
    if condition:
        decl += "#endif\n"
    return decl


def noising_A_decl(config: NoisingAKernelConfig) -> str:
    AxEBL_type = filename_type_to_cutlass_type[config.AxEBL_type]
    decl = f"\ttemplate void run_pearl_noising_A_<{AxEBL_type}, {config.R}, {config.tile_size_m}, {config.tile_size_k}, {config.pipeline_stages}>(PearlAPIParams&, cudaStream_t);\n"
    return decl


def noising_B_decl(config: NoisingBKernelConfig) -> str:
    EARxBpEB_type = filename_type_to_cutlass_type[config.EARxBpEB_type]

    decl = f"\ttemplate void run_pearl_noising_B_< {EARxBpEB_type}, {config.R}, {config.tile_size_n}, {config.tile_size_k}, {config.pipeline_stages}>(PearlAPIParams&, cudaStream_t);\n"
    return decl


def generate_instantiations(
    matmul_kernels: list[MatmulKernelConfig],
    noising_a_kernels: list[NoisingAKernelConfig],
    noising_b_kernels: list[NoisingBKernelConfig],
    output_dir: Path,
):
    SKIP_REDUCTION = [False, True]
    SKIP_DENOISING = [False, True]
    ENABLE_DEBUG = [False, True]
    OUTPUT_TYPES = ["bf16"]
    # create instantiations directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # clean out directory
    files = output_dir.glob("*.cu")
    for f in files:
        os.remove(f)

    # populate directory
    for config in matmul_kernels:
        for out_type in OUTPUT_TYPES:
            output_filename = f"gemm_R{config.R}_{out_type}_{config.tile_size_m}x{config.tile_size_n}x{config.tile_size_k}_{config.pipeline_stages}stages_cluster{config.cM}x{config.cN}.cu"
            output_file = Path(output_dir) / output_filename
            with open(output_file, "w") as fh:
                fh.write(f"#if !defined(DISABLE_R{config.R})")
                fh.write("\n" + noisy_gemm_prelude())
                for (
                    SkipReduction,
                    SkipDenoising,
                    EnableDebug,
                ) in itertools.product(
                    SKIP_REDUCTION,
                    SKIP_DENOISING,
                    ENABLE_DEBUG,
                ):
                    fh.write(
                        gemm_decl(
                            config,
                            out_type,
                            SkipReduction,
                            SkipDenoising,
                            EnableDebug,
                        )
                    )
                fh.write(f"#endif // #if !defined(DISABLE_R{config.R})")

    for config in noising_a_kernels:
        output_filename = f"noisingA_R{config.R}_{config.AxEBL_type}_{config.tile_size_m}x{config.tile_size_k}_{config.pipeline_stages}stages.cu"
        output_file = Path(output_dir) / output_filename
        with open(output_file, "w") as fh:
            fh.write(f"#if !defined(DISABLE_R{config.R})")
            fh.write("\n" + noising_A_prelude())
            fh.write(noising_A_decl(config))
            fh.write("#endif")

    for config in noising_b_kernels:
        output_filename = f"noisingB_R{config.R}_{config.EARxBpEB_type}_{config.tile_size_n}x{config.tile_size_k}_{config.pipeline_stages}stages.cu"
        output_file = Path(output_dir) / output_filename
        with open(output_file, "w") as fh:
            fh.write(f"#if !defined(DISABLE_R{config.R})")
            fh.write("\n" + noising_B_prelude())
            fh.write(noising_B_decl(config))
            fh.write("#endif")
